version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    workingworking_directory: /go/src/github.com/1k-ct/circleci_test
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...